Github Workflow for automated .deb package build
sergei-mironov/xkb-switch pull request #76
Opened 2024-07-31 20:36 UTC by brs-brs

This pull request introduces a GitHub Workflow for automating the build process of .deb packages. This enhancement aims to streamline the usage of xkb-switch for users on Debian-based systems, making it more convenient and accessible.

2024-08-01 19:37 UTC, sergei-mironov requested changes
Thanks for your work! I have just a few minor comments.

2024-08-01 19:37 UTC, sergei-mironov commented on .github/workflows/deb-build.yml
> +        cd build
I'm skeptical about tightening the project with the github-ci infrastructure, although I do appreciate the benefits of having latest .deb artifacts, even unchecked and unsigned. Could you please move `cpack` to a CMake rule and just call this rule from here?

2024-08-01 19:37 UTC, sergei-mironov commented on man/xkb-switch.1
> +.TH "xkb-switch" "1" "2.1.1" "J. Bromley, S. Mironov, Alexei Rad'kov" "User Commands"
Good catch, thanks!

2024-08-01 19:37 UTC, sergei-mironov commented on src/XKeyboard.cpp
> +  char* groupName = XGetAtomName(_display, desc->names->groups[xkbState.group]);
Could you please check the lengths before accessing this array element?

2024-08-03 16:27 UTC, brs-brs commented
Hi @sergei-mironov ! Now requested changes can be reviewed

2024-08-06 12:03 UTC, sergei-mironov approved these changes
Thanks, @brs-brs ! I will merge this PR into a branch and make some final adjustments

2024-08-06 12:03 UTC, merged